### ISSUE TITLE
Use better compressed image for the catgirl

### ISSUE THREAD

**Issue by Miepee** [lemon-sh/lemonsh.moe#2]
I compressed the catgirl image via pngquant, and got it down to 42kb instead of the original 260kb.
Consider using it instead please (am too lazy to clone and do a PR)
![okayucat-or8](https://user-images.githubusercontent.com/38186597/181500730-0fdd057f-9c17-4c23-972b-54bddc95dc56.png)

**Comment by lemon-sh** [comment]
the cat lost the eye color, unacceptable

**Comment by Miepee** [comment]
lemme use a little less compression then.

**Comment by Miepee** [comment]
This better? (73kb)
![okayucat-or8](https://user-images.githubusercontent.com/38186597/181505026-26cfc970-b017-49da-930f-f193b279823a.png)

**Comment by lemon-sh** [comment]
[yes](https://github.com/lemon-sh/lemonsh.moe/commit/68f1aa975a8796ae7d4f420c00e073e43f9321ba#diff-44c6b951d82aff985c73cdb7eb732195db6602cc2b4a3716136a79fd3fbde1f5)
