### ISSUE TITLE
Git is outdated

### ISSUE THREAD

**Issue by Miepee** [lemon-sh/lemonsh.moe#5]
It "links" to git.karx.xyz instead of the git.lemon something.

**Comment by lemon-sh** [comment]
[fixed](https://github.com/lemon-sh/lemonsh.moe/commit/9bac1cb7bdee9c631c8f32a16b308d455524efe5#diff-200abda264c3530e9cdb5d895e25d50bc3ed567079b39fe2ee3c1d1b5d661e09)
