### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by Miepee** [lemon-sh/lemonsh.moe#6]
A) Please consider hosting them on your own site, instead of phoning to google.
B) Consider minimizing the fonts, by taking out unnecessary glyphs (if possible)
C) Whats up with the copy pasted font-faces in the CSS?

**Comment by lemon-sh** [comment]
a) I will consider doing that
b) no, I don't wanna end up in a situation where I need a glyph but I stripped it out cause I thought I wouldn't need it.
c) it saves one layer of HTTP requests to google, yes, I benchmarked.
